// Fonte única de verdade do episódio. Lida pelo navegador (scene.js) e pelo
// Python (scripts/*.py), que extraem o objeto após "window.TIMELINE =".
// Mantenha JSON estrito aqui dentro: aspas duplas, sem comentários, sem vírgula final.
window.TIMELINE = {
  "episode": "ep01-estrelinha",
  "duration": 15.0,
  "fps": 30,
  "width": 1080,
  "height": 1920,
  "bpm": 128,
  "keys": {
    "groundStart": 0.0, "groundEnd": 0.4,
    "bodyStart": 0.12, "bodyEnd": 0.6, "fillIn": 0.48,
    "feet": 0.62, "eyes": 0.76, "mouth": 0.92, "sprout": 0.98, "sproutEnd": 1.28,
    "cheeks": 1.02, "grass": 1.12, "lookUp": 1.6, "twinkle": 1.75,
    "arms": 1.9, "reach": 2.1, "cloud": 2.3,
    "jump1": 3.3, "jump2": 3.9, "sad": 4.45, "perk": 5.35,
    "count1": 7.5, "count2": 8.4375, "count3": 9.375, "reachStar": 9.85,
    "reelStart": 10.35, "reelEnd": 11.1, "hop1": 11.2, "hop2": 12.1,
    "giggle": 12.95, "wink": 13.55, "starHop": 13.95, "starHopEnd": 14.4,
    "rewind": 14.42, "rewindEnd": 14.95
  },
  "narration": [
    { "id": "n01", "t": 0.15,   "text": "Olha! Uma estrelinha!" },
    { "id": "n02", "t": 2.05,   "text": "O Pituco quer pegar!" },
    { "id": "n03", "t": 3.32,   "text": "Pula!" },
    { "id": "n04", "t": 3.88,   "text": "Pula!" },
    { "id": "n05", "t": 4.5,    "text": "Não alcança!" },
    { "id": "n06", "t": 5.4,    "text": "Vamos ajudar? Conta comigo!" },
    { "id": "n07", "t": 7.5,    "text": "Um!" },
    { "id": "n08", "t": 8.4375, "text": "Dois!" },
    { "id": "n09", "t": 9.375,  "text": "Três!" },
    { "id": "n10", "t": 9.95,   "text": "Uau!" },
    { "id": "n11", "t": 11.8,   "text": "Conseguiu! Que brilho!" },
    { "id": "n12", "t": 13.55,  "text": "De novo?" }
  ],
  "sfx": [
    { "k": "groundStart", "s": "pencil", "dur": 0.4 },
    { "k": "groundStart", "s": "twinkle" },
    { "k": "bodyStart",   "s": "pencil", "dur": 0.48 },
    { "k": "feet",        "s": "pop", "pitch": 0.8 },
    { "k": "eyes",        "s": "pop", "pitch": 1.2 },
    { "k": "sprout",      "s": "boing", "pitch": 1.5, "gain": 0.6 },
    { "k": "lookUp",      "s": "voice_hm" },
    { "k": "twinkle",     "s": "plim" },
    { "k": "cloud",       "s": "pencil", "dur": 0.3, "gain": 0.5 },
    { "k": "jump1",       "s": "boing" },
    { "k": "jump2",       "s": "boing", "pitch": 1.15 },
    { "k": "sad",         "s": "slide_down" },
    { "k": "perk",        "s": "boing", "pitch": 1.6, "gain": 0.7 },
    { "k": "count1",      "s": "grow", "dur": 0.4 },
    { "k": "count1",      "s": "chime", "note": 72 },
    { "k": "count2",      "s": "grow", "dur": 0.4, "pitch": 1.25 },
    { "k": "count2",      "s": "chime", "note": 76 },
    { "k": "count3",      "s": "grow", "dur": 0.48, "pitch": 1.5 },
    { "k": "count3",      "s": "chime", "note": 79 },
    { "k": "reachStar",   "s": "plim", "pitch": 1.5 },
    { "k": "reachStar",   "s": "sparkle" },
    { "k": "reelStart",   "s": "whoosh", "dur": 0.7 },
    { "k": "reelEnd",     "s": "pop", "pitch": 1.4 },
    { "k": "reelEnd",     "s": "fanfare" },
    { "k": "reelEnd",     "s": "voice_yay", "o": 0.05 },
    { "k": "hop1",        "s": "boing", "pitch": 1.3, "gain": 0.6 },
    { "k": "hop2",        "s": "boing", "pitch": 1.45, "gain": 0.6 },
    { "k": "giggle",      "s": "voice_giggle" },
    { "k": "wink",        "s": "plim", "pitch": 2.0, "gain": 0.5 },
    { "k": "starHop",     "s": "boing", "pitch": 1.8, "gain": 0.7 },
    { "k": "starHop",     "s": "whoosh", "dur": 0.4, "gain": 0.6 },
    { "k": "rewind",      "s": "rewind", "dur": 0.55 }
  ]
};
